[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_simple_voting = "DBC3gQSeCsaJPJy31Q9Yar2E3y2DESKwpDGL6gjEGU5M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/silvestrevivo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
